name: flutter_competition
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  image_picker: ^0.8.5+3
  # di
  get_it: ^7.6.0
  # bloc state manager
  flutter_bloc: ^8.1.3
  # hive
  hive: ^2.2.3
  # equatable
  equatable: ^2.0.5
  # internet checker
  connectivity_plus: ^4.0.1
  # svg
  flutter_svg: ^2.0.7
  # show animation lotti file
  lottie: ^2.5.0
  # keyboard
  keyboard_dismisser: ^3.0.0
  # path
  path_provider: ^2.0.15
  # local notifications
  flutter_local_notifications: ^15.0.0
  # box
  gap: ^3.0.1
  # url launchers
  url_launcher: ^6.1.11
  # get location, permission and google maps
  google_maps_flutter: ^2.2.1
  map_picker: ^0.0.3
  geocoding: ^2.1.0
  location: ^5.0.1
  # snack bar
  flash: ^3.0.5+1
  # intl_utils
  intl_utils: ^2.8.3
  # animation button tap
  zoom_tap_animation: ^1.1.0

  # firebase
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.6.4
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_dynamic_links: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.2
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/localization/l10n
  preferred-supported-locales:
    - uz
  use-deferred-loading: true