name: flutter_competition
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  # di
  get_it: ^7.6.0
  # generating a string to state sha1
  crypto: ^3.0.3
  # html parse
  flutter_widget_from_html_core: ^0.10.2
  # bloc state manager
  flutter_bloc: ^8.1.3
  # sms auto fill
  pinput: ^2.2.31
  # forms
  formz: ^0.6.0
  # hive
  hive: ^2.2.3
  # equatable
  equatable: ^2.0.5
  # rest api
  dio: ^5.2.1+1
  # internet checker
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  # svg
  flutter_svg: ^2.0.7
  # keyboard
  keyboard_dismisser: ^3.0.0
  # path
  path_provider: ^2.0.15
  # firebase
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.6.4
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_dynamic_links: ^5.3.3
  # local notifications
  flutter_local_notifications: ^15.0.0
  # box
  gap: ^3.0.1
  # native splash
  flutter_native_splash: ^2.3.1
  # url launchers
  url_launcher: ^6.1.11
  # chuck
  chuck_interceptor: ^2.0.1
  # internet check
  # get location and permission
  geolocator_apple: ^2.2.7
  geolocator_android: ^4.1.9
  # permission
  permission_handler: ^10.4.1
  # for map launch in phone map
  map_launcher: ^2.5.0+1
  # uni link
  uni_links: ^0.5.1
  # package info
  package_info_plus: ^4.0.2
  # snack bar
  flash: ^3.0.5+1
  intl_utils: ^2.8.3
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.2
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/localization/l10n
  preferred-supported-locales:
    - uz
  use-deferred-loading: true